### ISSUE TITLE
Crash at run on 3D image

### ISSUE THREAD

**Issue by sebherbert** [weigertlab/napari-spotiflow#3]
**Describe the bug**
Crash during the run
 (error message reminds me of the error message on #2 )

**To Reproduce** 
Create a fresh environment and run on the linked image

Napari log =>
```
17:47:38 : INFO : MainThread : Predicting with (1, 6, 7, 1) tiles
INFO:spotiflow.model.spotiflow:Normalizing...
17:47:38 : INFO : MainThread : Normalizing...
INFO:spotiflow.model.spotiflow:Padding to shape (128, 896, 960, 1)
17:47:40 : INFO : MainThread : Padding to shape (128, 896, 960, 1)
/home/herber0000/miniconda3/envs/spotiflow/lib/python3.11/site-packages/spotiflow/utils/utils.py:587: RuntimeWarning: invalid value encountered in divide!

```

```
         [0.     ],
         [0.     ]]]], dtype=float32), (slice(0, 128, None), slice(128, 224, None), slice(128, 224, None), slice(0, 1, None)), (slice(0, 128, None), slice(608, 704, None), slice(320, 416, None), slice(0, 1, None)))
        iter_tiles = <generator object plugin_wrapper.<locals>.plugin.<locals>.progress.<locals>._progress at 0x7bfd210f9d40>
    993     tile, s_src, s_dst = item
    994     if isinstance(tile, da.Array):

File ~/miniconda3/envs/spotiflow/lib/python3.11/site-packages/napari_spotiflow/_dock_widget.py:253, in plugin_wrapper.<locals>.plugin.<locals>.progress.<locals>._progress(it=<generator object tile_iterator.<locals>._accumulate>, **kwargs={})
    251 for item in it:
    252     yield item
--> 253     progress_bar.increment(1)
        progress_bar = ProgressBar(value=<function match_type.<locals>.<lambda> at 0x7bfcb5f8b9c0>, annotation=<class 'magicgui.widgets.ProgressBar'>, name='progress_bar')
    254     app.process_events()
    255 app.process_events()

File ~/miniconda3/envs/spotiflow/lib/python3.11/site-packages/magicgui/widgets/_concrete.py:235, in ProgressBar.increment(self=ProgressBar(value=<function match_type.<locals>....icgui.widgets.ProgressBar'>, name='progress_bar'), val=1)
    233 def increment(self, val: float | None = None) -> None:
    234     """Increase current value by step size, or provided value."""
--> 235     self.value = self.get_value() + (val if val is not None else self.step)
        self = ProgressBar(value=<function match_type.<locals>.<lambda> at 0x7bfcb5f8b9c0>, annotation=<class 'magicgui.widgets.ProgressBar'>, name='progress_bar')
        val is not None = True
        val = 1

File ~/miniconda3/envs/spotiflow/lib/python3.11/site-packages/magicgui/widgets/bases/_ranged_widget.py:125, in RangedWidget.value(self=ProgressBar(value=<function match_type.<locals>....icgui.widgets.ProgressBar'>, name='progress_bar'), value=43)
    123 val: tuple[float, ...] = value if isinstance(value, tuple) else (value,)
    124 if any(float(v) < self.min or float(v) > self.max for v in val):
--> 125     raise ValueError(
        value = 43
        self = ProgressBar(value=<function match_type.<locals>.<lambda> at 0x7bfcb5f8b9c0>, annotation=<class 'magicgui.widgets.ProgressBar'>, name='progress_bar')
    126         f"value {value} is outside of the allowed range: "
    127         f"({self.min}, {self.max})"
    128     )
    129 ValueWidget.value.fset(self, value)

EmitLoopError: 

While emitting signal 'magicgui.widgets.PushButton.changed', a ValueError occurred in a callback:

  Signal emitted at: /home/herber0000/miniconda3/envs/spotiflow/lib/python3.11/site-packages/magicgui/widgets/bases/_value_widget.py:71, in _on_value_change
    >  self.changed.emit(value)

  Callback error at: /home/herber0000/miniconda3/envs/spotiflow/lib/python3.11/site-packages/magicgui/widgets/bases/_ranged_widget.py:125, in value
    >  raise ValueError(

    Local variables:
       value = 43
       val = (43,)

See ValueError above for original traceback.

```

**Environment (please complete the following information):**
 - Spotiflow version: [0.5.0]
 - napari-spotiflow version: [0.3.3]
 - Conda/mamba version (if applicable): [conda 24.7.1]
 - OS: [Ubuntu]
 - OS version: [Ubuntu 24.04]
 - GPU memory (if applicable): GTX 1080 - 8192MiB 
 - napari version: [0.5.4]
 - python version: 3.11.10

**Additional context**
The plugin runs with the sample images (2D Hybiss and Synth3D), but crashes with a 3D image of 951*882 pixels * 120 z slices. Dataset is here if it can be useful :) https://drive.switch.ch/index.php/s/a9CS1XXHVPFExJH

**Comment by AlbertDominguez** [comment]
Hi @sebherbert, thanks for the thorough report and the sample image, I could replicate and seems to be an issue with the way we use the progress bar to monitor progress (everything needs a big refactor anyway which I hope I have time to do soon 🙂) . I've just released a fix in this repository, and also pushed a necessary change to the main Spotiflow repository. I'm planning to release a new version of the main repository probably next week, but in the meanwhile, installing from the repo should suffice. So, could you do
`$ pip install -U git+https://github.com/weigertlab/spotiflow/git napari-spotiflow`
and try again? Lmk if it works for you so I can close the issue

P.S. the data seems pretty diff from our 3D training sets, which are unfortunately rather small. Feel free to reach out if you think performance should be improved, happy to discuss

**Comment by sebherbert** [comment]
Hi! 
Thanks for the quick feedback!
It all worked smoothly after I understood that I was missing a local g++ install :) 

Results are looking promising for the moment. I wanted to run a quick test before the SwissBIAS workshop next week, I'll be happy to discuss the results with you!
![image](https://github.com/user-attachments/assets/a8bad758-2e7a-405f-bfb5-ebbc6c994d2d)
